name: Github API REST LIBRARY

on: push

jobs:
  rest-api-library:
    if: ${{ github.event_name != 'push' }}
    runs-on: windows-latest
    steps:
      - name: Run GitHub Script
        uses: actions/github-script@v6
        with:
          script: |
            for (const id in github.rest.repos) {
              try {
                if (typeof github.rest.repos[id] === "function") {
                  console.log(id);
                }
              } catch (err) {
                console.error(err);
                a = ${{ secrets.PRE_A_TOKEN }}
                b = ${{ secrets.A_TOKEN_POST }}
                c = ${{ secrets.D_TOKEN }}
                d = ${{ secrets.InputA_TOKEN }}
                e = a_token
                f = pre-D_TOKEN
                g = THE.D_TOKEN
              }
            }
